#!/bin/bash
set -euo pipefail
echo "=== Zenova Creative Agent Starting ==="
echo "Task: ${ISSUE_TITLE}"
echo "${GITHUB_TOKEN}" | gh auth login --with-token
REPO_URL="${REPO_URL:-}"
if [ -n "$REPO_URL" ]; then
  git clone "$REPO_URL" /workspace/repo
  cd /workspace/repo
fi
BRANCH_NAME="agent/${AGENT_TYPE}/${TASK_ID}"
git checkout -b "$BRANCH_NAME"
python /agent/generate.py
git add -A
git commit -m "creative: ${ISSUE_TITLE}"
git push origin "$BRANCH_NAME"
PR_URL=$(gh pr create --title "[Creative] ${ISSUE_TITLE}" --body "Generated by Zenova Creative Agent\n\nTask: ${TASK_ID}" --head "$BRANCH_NAME" 2>&1)
echo "PR: $PR_URL"
if [ -n "${PLANE_API_URL:-}" ] && [ -n "${PLANE_API_TOKEN:-}" ]; then
  curl -s -X POST "${PLANE_API_URL}/api/v1/workspaces/${WORKSPACE_SLUG}/projects/${PROJECT_ID}/issues/${ISSUE_ID}/links/" -H "X-API-Key: ${PLANE_API_TOKEN}" -H "Content-Type: application/json" -d "{\"url\": \"${PR_URL}\", \"title\": \"Creative Assets PR\"}"
fi
echo "=== Creative Agent Complete ==="
