#!/bin/bash
set -euo pipefail
echo "=== Zenova Strategy Agent Starting ==="
echo "Task: ${ISSUE_TITLE}"
echo "${GITHUB_TOKEN}" | gh auth login --with-token
REPO_URL="${REPO_URL:-}"
if [ -n "$REPO_URL" ]; then
  git clone "$REPO_URL" /workspace/repo
  cd /workspace/repo
fi
BRANCH_NAME="agent/${AGENT_TYPE}/${TASK_ID}"
git checkout -b "$BRANCH_NAME"

SAFE_TITLE=$(echo "${ISSUE_TITLE}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | head -c 50)
OUTPUT_DIR="/workspace/repo/docs/strategy"
OUTPUT_FILE="${OUTPUT_DIR}/${SAFE_TITLE}.md"
mkdir -p "$OUTPUT_DIR"

# Write prompts to files to avoid shell injection
SYSTEM_PROMPT_FILE=$(mktemp)
USER_PROMPT_FILE=$(mktemp)
cat /agent/prompt.md > "$SYSTEM_PROMPT_FILE"
cat > "$USER_PROMPT_FILE" <<PROMPT_EOF
## Current Task
**Issue:** ${ISSUE_TITLE}
**Description:** ${ISSUE_DESCRIPTION}

Generate a comprehensive strategy document for this task. Output only the Markdown content of the document.
PROMPT_EOF

# Pass file paths via env vars so Python reads them safely
SYSTEM_PROMPT_FILE="$SYSTEM_PROMPT_FILE" \
USER_PROMPT_FILE="$USER_PROMPT_FILE" \
OUTPUT_FILE="$OUTPUT_FILE" \
python3 -c "
import os, anthropic

client = anthropic.Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])

with open(os.environ['SYSTEM_PROMPT_FILE']) as f:
    system_prompt = f.read()
with open(os.environ['USER_PROMPT_FILE']) as f:
    user_prompt = f.read()

message = client.messages.create(
    model='claude-sonnet-4-20250514',
    max_tokens=4096,
    system=system_prompt,
    messages=[{'role': 'user', 'content': user_prompt}],
)
text = message.content[0].text
output_file = os.environ['OUTPUT_FILE']
with open(output_file, 'w') as f:
    f.write(text)
print(f'Generated: {output_file}')
"

rm -f "$SYSTEM_PROMPT_FILE" "$USER_PROMPT_FILE"

git add -A
git commit -m "strategy: ${ISSUE_TITLE}"
git push origin "$BRANCH_NAME"
PR_URL=$(gh pr create --title "[Strategy] ${ISSUE_TITLE}" --body "Generated by Zenova Strategy Agent\n\nTask: ${TASK_ID}" --head "$BRANCH_NAME" 2>&1)
echo "PR: $PR_URL"
if [ -n "${PLANE_API_URL:-}" ] && [ -n "${PLANE_API_TOKEN:-}" ]; then
  # Use jq for safe JSON construction
  jq -n --arg url "$PR_URL" --arg title "Strategy Document PR" '{url: $url, title: $title}' | \
    curl -s -X POST "${PLANE_API_URL}/api/v1/workspaces/${WORKSPACE_SLUG}/projects/${PROJECT_ID}/issues/${ISSUE_ID}/links/" \
      -H "X-API-Key: ${PLANE_API_TOKEN}" -H "Content-Type: application/json" -d @-
  jq -n --arg html "<p>Strategy agent completed. PR: ${PR_URL}</p>" '{comment_html: $html}' | \
    curl -s -X POST "${PLANE_API_URL}/api/v1/workspaces/${WORKSPACE_SLUG}/projects/${PROJECT_ID}/issues/${ISSUE_ID}/comments/" \
      -H "X-API-Key: ${PLANE_API_TOKEN}" -H "Content-Type: application/json" -d @-
fi
echo "=== Strategy Agent Complete ==="
